CREATE DATEBASE ANIME;

USE ANIME;

CREATE TABLE name(
	AnimeID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	AnimeTitle VARCHAR(100) NOT NULL,
	UNIQUE(AnimeTitle)
);

CREATE TABLE info(
	AnimeID INT NOT NULL,
	AnimeEpisode VARCHAR(100) NOT NULL,
	AnimeMagnet VARCHAR(100) NOT NULL,
	FOREIGN KEY(AnimeID) REFERENCES name(AnimeID)
);